/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AskAjRouteImport } from './routes/ask-aj'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing.index'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiAskAjRouteImport } from './routes/api.ask-aj'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AskAjRoute = AskAjRouteImport.update({
  id: '/ask-aj',
  path: '/ask-aj',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskAjRoute = ApiAskAjRouteImport.update({
  id: '/api/ask-aj',
  path: '/api/ask-aj',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask-aj': typeof AskAjRoute
  '/contact': typeof ContactRoute
  '/engineering': typeof EngineeringRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/systems': typeof SystemsRoute
  '/timeline': typeof TimelineRoute
  '/work': typeof WorkRoute
  '/api/ask-aj': typeof ApiAskAjRoute
  '/api/contact': typeof ApiContactRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask-aj': typeof AskAjRoute
  '/contact': typeof ContactRoute
  '/engineering': typeof EngineeringRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/systems': typeof SystemsRoute
  '/timeline': typeof TimelineRoute
  '/work': typeof WorkRoute
  '/api/ask-aj': typeof ApiAskAjRoute
  '/api/contact': typeof ApiContactRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask-aj': typeof AskAjRoute
  '/contact': typeof ContactRoute
  '/engineering': typeof EngineeringRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/systems': typeof SystemsRoute
  '/timeline': typeof TimelineRoute
  '/work': typeof WorkRoute
  '/api/ask-aj': typeof ApiAskAjRoute
  '/api/contact': typeof ApiContactRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask-aj'
    | '/contact'
    | '/engineering'
    | '/sitemap.xml'
    | '/systems'
    | '/timeline'
    | '/work'
    | '/api/ask-aj'
    | '/api/contact'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask-aj'
    | '/contact'
    | '/engineering'
    | '/sitemap.xml'
    | '/systems'
    | '/timeline'
    | '/work'
    | '/api/ask-aj'
    | '/api/contact'
    | '/writing/$slug'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/ask-aj'
    | '/contact'
    | '/engineering'
    | '/sitemap.xml'
    | '/systems'
    | '/timeline'
    | '/work'
    | '/api/ask-aj'
    | '/api/contact'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskAjRoute: typeof AskAjRoute
  ContactRoute: typeof ContactRoute
  EngineeringRoute: typeof EngineeringRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SystemsRoute: typeof SystemsRoute
  TimelineRoute: typeof TimelineRoute
  WorkRoute: typeof WorkRoute
  ApiAskAjRoute: typeof ApiAskAjRoute
  ApiContactRoute: typeof ApiContactRoute
  WritingSlugRoute: typeof WritingSlugRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-aj': {
      id: '/ask-aj'
      path: '/ask-aj'
      fullPath: '/ask-aj'
      preLoaderRoute: typeof AskAjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask-aj': {
      id: '/api/ask-aj'
      path: '/api/ask-aj'
      fullPath: '/api/ask-aj'
      preLoaderRoute: typeof ApiAskAjRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskAjRoute: AskAjRoute,
  ContactRoute: ContactRoute,
  EngineeringRoute: EngineeringRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SystemsRoute: SystemsRoute,
  TimelineRoute: TimelineRoute,
  WorkRoute: WorkRoute,
  ApiAskAjRoute: ApiAskAjRoute,
  ApiContactRoute: ApiContactRoute,
  WritingSlugRoute: WritingSlugRoute,
  WritingIndexRoute: WritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
